"use client";

/**
 * Client barrel for the Fluent System Icons.
 *
 * @fluentui/react-icons builds its styles through griffel, which runs only on
 * the client. Importing an icon straight into a server component therefore
 * fails at build time with "Attempted to call __styles() from the server".
 * Re-exporting them across a "use client" boundary hands server components a
 * client reference instead, which they can render freely.
 *
 * Import every icon from here, never from the package directly.
 */
export {
  Add16Regular,
  Alert16Regular,
  ApprovalsApp16Regular,
  Archive16Regular,
  ArrowCounterclockwise16Regular,
  ArrowDown16Regular,
  ArrowDownload16Regular,
  ArrowLeft16Regular,
  ArrowRight16Regular,
  ArrowSwap16Regular,
  ArrowSync16Regular,
  ArrowUp16Regular,
  ArrowUpRight16Regular,
  Beaker16Regular,
  Board16Regular,
  BookOpen16Regular,
  BoxMultipleRegular,
  Calculator16Regular,
  CalendarLtr16Regular,
  Camera16Regular,
  ChatWarning16Regular,
  CheckboxChecked16Regular,
  Checkmark16Regular,
  CheckmarkCircle16Regular,
  CheckmarkStarburst16Regular,
  ChevronDown16Regular,
  ChevronUpDown16Regular,
  Circle16Regular,
  ClipboardCheckmark16Regular,
  ClipboardTaskListLtrRegular,
  CloudOff16Regular,
  Copy16Regular,
  DataBarVertical16Regular,
  Delete16Regular,
  Dismiss16Regular,
  DismissCircle16Regular,
  Fire16Regular,
  ImageOffRegular,
  Info16Regular,
  Key16Regular,
  LayerRegular,
  LeafOne16Regular,
  Location16Regular,
  LockClosed16Regular,
  Mail16Regular,
  Money16Regular,
  Navigation16Regular,
  Note16Regular,
  Organization16Regular,
  People16Regular,
  PersonAdd16Regular,
  PlantGrassRegular,
  PlugDisconnected16Regular,
  PowerRegular,
  Print16Regular,
  Prohibited16Regular,
  Ribbon16Regular,
  Rss16Regular,
  Save16Regular,
  Scales16Regular,
  Settings16Regular,
  ShieldCheckmark16Regular,
  ShieldError16Regular,
  SignOutRegular,
  Sparkle16Regular,
  SpinnerIos16Regular,
  Temperature16Regular,
  TextPercent16Regular,
  ThumbDislike16Regular,
  ThumbLike16Regular,
  VehicleTruck16Regular,
  Wallet16Regular,
  Warning16Regular,
  Beaker20Regular,
  Board20Regular,
  CheckboxChecked20Regular,
  DataBarVertical20Regular,
  Fire20Regular,
  LeafOne20Regular,
  Location20Regular,
  Organization20Regular,
  People20Regular,
  Ribbon20Regular,
  Scales20Regular,
  Settings20Regular,
  ShieldCheckmark20Regular,
  Wallet20Regular,
  Beaker20Filled,
  Board20Filled,
  BoxMultipleFilled,
  CheckboxChecked20Filled,
  ClipboardTaskListLtrFilled,
  DataBarVertical20Filled,
  Fire20Filled,
  LeafOne20Filled,
  Location20Filled,
  Organization20Filled,
  People20Filled,
  PlantGrassFilled,
  Ribbon20Filled,
  Scales20Filled,
  Settings20Filled,
  ShieldCheckmark20Filled,
  Wallet20Filled,
  BookDatabase20Filled,
  BoxMultiple20Filled,
  BuildingFactory20Filled,
  ClipboardCheckmark20Filled,
  DataTrending20Filled,
  Flowchart20Filled,
  Home20Filled,
  LeafThree20Filled,
  Molecule20Filled,
  Notepad20Filled,
  PlantGrass20Filled,
  Vault20Filled,
} from "@fluentui/react-icons";

export type { FluentIcon } from "@fluentui/react-icons";
